### ISSUE TITLE
Solve .gitignore problem.

### ISSUE THREAD

**Issue by surajwate** [surajwate/coding2020#2]
The _journal.txt_ is still getting updated in **Git** after adding the file in _.gitignore_ file. 
**Git** should ignore the _journal.txt_ file.

**Comment by niemtec** [comment]
This might be helpful: [Why is .gitignore not ignoring my files?](https://stackoverflow.com/questions/45400361/why-is-gitignore-not-ignoring-my-files)

**Comment by surajwate** [comment]
Thank you @niemtec
